name: cspell

on:
  pull_request:
    branches:
      - cluster
      - master
    paths:
      - 'docs/**'
  push:
    # branches:
    #   - cluster
    #   - master
    paths:
      - 'docs/**'
  workflow_dispatch: {}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  cspell:
    name: Run cspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: streetsidesoftware/cspell-action@v6
