name: pre-commit

on:
  pull_request:
    branches:
      - cluster
      - master
    paths:
      - 'docs/**'
  push:
    # branches:
    #   - cluster
    #   - master
    paths:
      - 'docs/**'
  workflow_dispatch: {}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20.x

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up pre-commit
        run: make pre-commit-setup

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
