name: pre-commit

on:
  pull_request:
    branches:
      - cluster
      - master
    paths:
      - 'docs/**'
  push:
    branches:
      - cluster
      - master
    paths:
      - 'docs/**'
  workflow_dispatch: {}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          check-latest: true
          python-version: '3.12'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
